[[languages]]
name = "Rust"
dir = "language"
file = "main.rs"
compile = "rustc $FILE"
version = "rustc --version"
webpage = "https://www.rust-lang.org/"

[[languages]]
name = "Go"
dir = "language"
file = "main.go"
compile = "go build $FILE"
version = "go version"
webpage = "https://golang.org/"

[[languages]]
name = "C (gcc)"
dir = "language"
file = "main.c"
compile = "gcc -Wall $FILE"
version = "gcc --version"
webpage = "https://gcc.gnu.org/"

[[languages]]
name = "C (clang)"
dir = "language"
file = "main.c"
compile = "clang -Wall $FILE"
version = "clang --version"
webpage = "https://clang.llvm.org/"

[[languages]]
name = "Elm"
dir = "language/elm"
file = "src/Main.elm"
compile = "elm make $FILE"
version = "elm --version"
webpage = "https://elm-lang.org/"